---
- name: deploy | install docker-compose
  package:
    name: docker-compose
    state: present
- name: deploy | install docker
  package:
    name: docker
    state: present
- name: deploy | enable private registry
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    mode: "0755"
- name: deploy | restart docker service
  service:
    name: docker
    state: reloaded